src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $result_date = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    private ?Admin $admin = null;

    /**
     * @var Collection<int, Participation>
     */
    #[ORM\OneToMany(targetEntity: Participation::class, mappedBy: 'game_id')]
    private Collection $participations;

    /**
     * @var Collection<int, Guess>
     */
    #[ORM\OneToMany(targetEntity: Guess::class, mappedBy: 'game_id')]
    private Collection $guesses;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
        $this->guesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getResultDate(): ?\DateTimeInterface
    {
        return $this->result_date;
    }

    public function setResultDate(\DateTimeInterface $result_date): static
    {
        $this->result_date = $result_date;

        return $this;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): static
    {
        $this->admin = $admin;

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): static
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setGameId($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): static
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getGameId() === $this) {
                $participation->setGameId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Guess>
     */
    public function getGuesses(): Collection
    {
        return $this->guesses;
    }

    public function addGuess(Guess $guess): static
    {
        if (!$this->guesses->contains($guess)) {
            $this->guesses->add($guess);
            $guess->setGameId($this);
        }
        return $this;
    }

    public function removeGuess(Guess $guess): static
    {
        if ($this->guesses->removeElement($guess)) {
            // set the owning side to null (unless already changed)
            if ($guess->getGameId() === $this) {
                $guess->setGameId(null);
            }
        }
        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Admin;
use App\Entity\Game;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('end_date', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('result_date', DateTimeType::class, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Patient;
use App\Form\PatientType;
use App\Entity\Participant;
use App\Form\ParticipantType;
use App\Entity\Game;
use App\Form\GameType;
use Symfony\Component\Uid\Uuid;
use App\Entity\Admin;

class GameController extends AbstractController
{
    #[Route('/game', name: 'app_game')]
    public function index(): Response
    {
        return $this->render('game/index.html.twig', [
            'controller_name' => 'GameController',
        ]);
    }

    #[Route('/create-patient', name: 'create_patient')]
    public function createPatient(Request $request, EntityManagerInterface $entityManager): Response
    {
        $patient = new Patient();

        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $admin = $this->getUser();
            $patient->setAdmin($admin);

            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('create_patient');
        }
        $patient = $entityManager->getRepository(Patient::class)->findAll();

        return $this->render('game/patient.html.twig', [
            'patientForm' => $form->createView(),
            'patients' => $patient,
        ]);
    }

    #[Route('/create-participant', name: 'create_participant')]
    public function createParticipant(Request $request, EntityManagerInterface $entityManager): Response
    {
        $participant = new Participant();
        $participantForm = $this->createForm(ParticipantType::class, $participant);
        $participantForm->handleRequest($request);

        if ($participantForm->isSubmitted() && $participantForm->isValid()) {
            $admin = $this->getUser();
            $participant->setAdmin($admin);

            $entityManager->persist($participant);
            $entityManager->flush();

            return $this->redirectToRoute('create_participant');
        }

        $participants = $entityManager->getRepository(Participant::class)->findAll();

        $game = new Game();
        $gameForm = $this->createForm(GameType::class, $game);
        $gameForm->handleRequest($request);

        if ($gameForm->isSubmitted() && $gameForm->isValid()) {
            $admin = $this->getUser();
            $game->setAdmin($admin);

            $entityManager->persist($game);
            $entityManager->flush();

            return $this->redirectToRoute('create_participant');
        }

        $games = $entityManager->getRepository(Game::class)->findAll();

        return $this->render('game/participant.html.twig', [
            'participantForm' => $participantForm->createView(),
            'participants' => $participants,
            'gameForm' => $gameForm->createView(),
            'games' => $games,

        ]);
    }

    #[Route('/paiement', name: 'app_paiement')]
    public function paiement(EntityManagerInterface $entityManager): Response
    {
        /** @var Admin $admin */
        $admin = $this->getUser();

        $patients = $admin->getPatients();

        if ($patients->isEmpty()) {
            throw $this->createNotFoundException('Aucun patient trouvé.');
        }

        $patient = $patients->first();

        if (!$patient || !$patient->getName()) {
            throw $this->createNotFoundException('Patient sans nom trouvé.');
        }

        $game = $entityManager->getRepository(Game::class)->findOneBy(['admin' => $admin]);

        if (!$game) {
            throw $this->createNotFoundException('Aucun jeu trouvé.');
        }
    
        $token = Uuid::v4();
        $privateLink = 'https://ton-jeu.com/participation?token=' . $token;
    
        return $this->render('game/paiement.html.twig', [
            'privateLink' => $privateLink,
            'patient' => $patient,
            'game' => $game,
        ]);
    }
}    

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}
    <h1>Donnée pour initier le jeu</h1>
    <a href="{{ path('create_patient') }}">Ajouter un patient</a>

{% endblock %}

templates/game/paiement.html.twig
{% extends 'base.html.twig' %}

{% block title %}paiement{% endblock %}

{% block body %}

<h1>Page de paiement</h1>

<p>Merci pour votre achat ! Voici le lien vers votre espace privé :</p>

<div>
    <label for="prewrittenMessage">Message à envoyer aux participants :</label>
    <textarea id="prewrittenMessage" rows="4" cols="50" readonly>
        Bonjour,
        
        Vous êtes invité à participer à notre jeu pour aider {{ patient.name }} à passer ce douloureux moment.
        La date limite pour jouer est le {{ game.endDate ? game.endDate|date('d/m/Y H:i') : 'N/A' }} et les résultats seront affichés le {{ game.resultDate ? game.resultDate|date('d/m/Y H:i') : 'N/A' }}.
        Cliquez sur le lien suivant pour accéder à votre espace privé et participer : {{ privateLink }}

        Merci de votre participation !
    </textarea>
    <button onclick="copyMessage()">Copier le message</button>
</div>
<p>Vous pouvez aussi copier le lien suivant pour l'envoyer à vos participants en sms ou email et ils auront accés au jeu:</p>

<script>

function copyMessage() {
    var copyText = document.getElementById("prewrittenMessage");
    copyText.select();
    document.execCommand("copy");
    alert("Message copié !");
}
</script>

{% endblock %}

templates/game/participant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}

    <h1>Configurer les horaires de jeu</h1>
    {{ form_start(gameForm) }}
        {{ form_row(gameForm.end_date, {'label': 'horaire de fin de participation'}) }}
        {{ form_row(gameForm.result_date, {'label': 'horaire de fin de jeu du patient et affichage des résultat'}) }}
        <button type="submit" class="btn">Enregistrer les horaires</button>
    {{ form_end(gameForm) }}

    {% for game in games %}
        <li>{{ game.endDate|date('d/m/Y H:i') }} - {{ game.resultDate|date('d/m/Y H:i') }}</li>
    {% else %}
        <li>Aucun horaire enregistré pour l'instant.</li>
    {% endfor %}

    <hr>

    <h1>Selectionné le nombre de participants</h1>

    <a href="{{ path('app_paiement')}}" class="btn btn-primary">De 1 à 20 participants <br>0.99€</a>
<a href="{{ path('app_paiement')}}" class="btn btn-primary">De 21 à 50 participants <br>1.99€</a>
<a href="{{ path('app_paiement') }}" class="btn btn-primary">Au-delà de 50 participants <br>4.99€</a>



   <h2>Participants enregistrés</h2>
    <ul>
        {% for participant in participants %}
            <li>{{ participant.name }} - {{ participant.phone }} - {{ participant.email }}</li>
        {% else %}
            <li>Aucun participant enregistré pour l'instant.</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/game/patient.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}
    <h1>Données du patient</h1>
    {{ form_start(patientForm) }}
        {{ form_row(patientForm.name, {'label': 'Nom du patient'}) }}
        {{ form_row(patientForm.phone, {'label': 'Numéro de téléphone'}) }}
        <button type="submit" class="btn">Enregistrer le patient</button>
    {{ form_end(patientForm) }}

    <ul>
        {% for patient in patients %}
            <li>{{ patient.name }} - {{ patient.phone }}</li>
        {% else %}
            <li>Aucun participant enregistré pour l'instant.</li>
        {% endfor %}
    </ul>

    <a href="{{ path('create_participant') }}" class="btn">Gérer les participants</a>
{% endblock %}

templates/game/sendSms.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}
<h1>Envoyer un SMS aux participants</h1>
<p>Cliquez sur un numéro pour envoyer un SMS à chaque participant.</p>

<ul>
    {% for sms in smsLinks %}
        <li>
            {{ sms.name }} - <a href="{{ sms.link }}">Envoyer un SMS à {{ sms.phone }}</a>
        </li>
    {% else %}
        <li>Aucun participant trouvé.</li>
    {% endfor %}
</ul>
{% endblock %}